---
name: Checks

on: [push]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    name: Test
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get pytest
        run: pip3 install pytest

      - name: Get pytest-mock
        run: pip3 install pytest-mock

      - name: Get package
        run: pip3 install -e .

      - name: Test
        run: pytest -v tests/.
