---

name: Checks

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get pytest
        run: pip3 install pytest
      - name: Get pytest-mock
        run: pip3 install pytest-mock
      - name: Get package
        run: pip3 install -e .
      - name: Test
        run: pytest -v tests/.
  test:
      name: TestUV
      runs-on: ubuntu-24.04
      steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install UV 
        uses: astral-sh/setup-uv@v6
      - name: Get package
        run: uv pip install -e .
      - name: Install Ruff
        uses: uv pip install ruff
      - name: run ruff
        uses: uv run ruff check .
      - name: Install pytest
        uses: uv pip install pytest
      - name: run pytest tests
        uses: uv run pytest -v tests/.
